### ISSUE TITLE
Question: Can I run a tor snowflake relay using this docker container?

### ISSUE THREAD

**Issue by pirate** [cohosh/snowbox#2]
Apologies if I'm misunderstanding the purpose of the repo, but can I use this to self-host a tor snowflake relay, or is this repo for only for testing the snowflake tunnel system itself?

**Comment by Hashik-Donthineni** [comment]
Hey @pirate! this repo is used to simulate a Snowflake client and broker to aid and test the development of Snowflake proxy on various platforms (ex: Web-extension, mobile app).

 I'm sorry I am not sure what you meant by "Snowflake relay" tho, do you mean a Snowflake proxy, you can run [Snowflake web extension](https://snowflake.torproject.org/) to help users circumvent censorship by relaying the data :smiley:

**Comment by pirate** [comment]
I want to help users circumvent censorship but from my headless server, without running a full browser just to run the extension. Is there a docker container somewhere that lets me do that?

**Comment by Hashik-Donthineni** [comment]
Ah, that makes sense. But unfortunately, that's not possible with Snowflake for now (pinging @cohosh for confirmation) but since you are saying it's a headless server which presumably runs 24/7, I would say [Obfs4 bridge](https://community.torproject.org/relay/setup/bridge/) is the best option for you to help censored users, there is also a [Docker container for Obfs4](https://gitlab.torproject.org/tpo/anti-censorship/docker-obfs4-bridge). Please let me know if you have any other queries. Thank you for considering to help!

**Comment by pirate** [comment]
Ah ok, I already run an Obfs4 bridge I think, thanks anyway!

**Comment by Hashik-Donthineni** [comment]
@pirate I might be wrong. There is a non-browser-based proxy at [Snowflake](https://gitweb.torproject.org/pluggable-transports/snowflake.git/tree/proxy). I am not sure if this is intended for "server" purpose or just for testing, we need @cohosh to answer this, she is one of the devs behind Snowflake repo. So, I suggest keeping the ticket open until she responds.

**Comment by cohosh** [comment]
Hi @pirate. Snowbox is a development environment for working on and testing changes to snowflake.

You can run a snowflake proxy without running a browser by running the standalone proxy, which is written in Go. We don't have it set up in a Docker environment at the moment, but it might be a good idea to make a ticket for that. As it is, as long as you have Go installed on your machine, it's fairly easy to build and set it up. I just created an issue for it over on our main snowflake repo: https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/issues/40002

You can track that if you want to receive updates. Thanks for requesting the feature!

**Comment by pirate** [comment]
Awesome! For context, the server I'd run snowflake on has dozens of other services on it with wildly different requirements, so as a matter of policy everything must run in docker containers to avoid contaminating the host setup. Thanks for making that ticket @cohosh and I'll keep an eye on it for updates!
